export const EXTENDED_TRANSPORT_CHANNEL = 13 // MIDI channel 14, zero-indexed

export interface ExtendedTransportCommand {
  id: string
  label: string
  command: string
  group: string
}

// Note number = array index. See docs/superpowers/specs/2026-07-13-cubase-companion-extended-transport-design.md
// (Command table section) -- this array must stay in the exact same order as the
// EXTENDED_TRANSPORT_COMMANDS array in the Cubase script (Cubanion_Transport.js).
export const EXTENDED_TRANSPORT_COMMANDS: ExtendedTransportCommand[] = [
  { id: 'setLeftLocator', label: 'Set Left Locator', command: 'Set Left Locator', group: 'Locators' },
  { id: 'setRightLocator', label: 'Set Right Locator', command: 'Set Right Locator', group: 'Locators' },
  { id: 'toLeftLocator', label: 'To Left Locator', command: 'To Left Locator', group: 'Locators' },
  { id: 'toRightLocator', label: 'To Right Locator', command: 'To Right Locator', group: 'Locators' },
  { id: 'exchangeLocatorPositions', label: 'Exchange Locator Positions', command: 'Exchange Locator Positions', group: 'Locators' },
  { id: 'locatorsToSelection', label: 'Locators to Selection', command: 'Locators to Selection', group: 'Locators' },
  { id: 'inputLeftLocator', label: 'Input Left Locator', command: 'Input Left Locator', group: 'Locators' },
  { id: 'inputRightLocator', label: 'Input Right Locator', command: 'Input Right Locator', group: 'Locators' },
  { id: 'inputLocatorDuration', label: 'Input Locator Duration', command: 'Input Locator Duration', group: 'Locators' },
  { id: 'inputPosition', label: 'Input Position', command: 'Input Position', group: 'Locators' },
  { id: 'insertCycleMarker', label: 'Insert Cycle Marker', command: 'Insert Cycle Marker', group: 'Cycle Markers' },
  { id: 'toCycleMarker1', label: 'To Cycle Marker 1', command: 'To Cycle Marker 1', group: 'Cycle Markers' },
  { id: 'toCycleMarker2', label: 'To Cycle Marker 2', command: 'To Cycle Marker 2', group: 'Cycle Markers' },
  { id: 'toCycleMarker3', label: 'To Cycle Marker 3', command: 'To Cycle Marker 3', group: 'Cycle Markers' },
  { id: 'toCycleMarker4', label: 'To Cycle Marker 4', command: 'To Cycle Marker 4', group: 'Cycle Markers' },
  { id: 'toCycleMarker5', label: 'To Cycle Marker 5', command: 'To Cycle Marker 5', group: 'Cycle Markers' },
  { id: 'toCycleMarker6', label: 'To Cycle Marker 6', command: 'To Cycle Marker 6', group: 'Cycle Markers' },
  { id: 'toCycleMarker7', label: 'To Cycle Marker 7', command: 'To Cycle Marker 7', group: 'Cycle Markers' },
  { id: 'toCycleMarker8', label: 'To Cycle Marker 8', command: 'To Cycle Marker 8', group: 'Cycle Markers' },
  { id: 'toCycleMarker9', label: 'To Cycle Marker 9', command: 'To Cycle Marker 9', group: 'Cycle Markers' },
  { id: 'toCycleMarkerX', label: 'To Cycle Marker X', command: 'To Cycle Marker X', group: 'Cycle Markers' },
  { id: 'recallCycleMarker1', label: 'Recall Cycle Marker 1', command: 'Recall Cycle Marker 1', group: 'Cycle Markers' },
  { id: 'recallCycleMarker2', label: 'Recall Cycle Marker 2', command: 'Recall Cycle Marker 2', group: 'Cycle Markers' },
  { id: 'recallCycleMarker3', label: 'Recall Cycle Marker 3', command: 'Recall Cycle Marker 3', group: 'Cycle Markers' },
  { id: 'recallCycleMarker4', label: 'Recall Cycle Marker 4', command: 'Recall Cycle Marker 4', group: 'Cycle Markers' },
  { id: 'recallCycleMarker5', label: 'Recall Cycle Marker 5', command: 'Recall Cycle Marker 5', group: 'Cycle Markers' },
  { id: 'recallCycleMarker6', label: 'Recall Cycle Marker 6', command: 'Recall Cycle Marker 6', group: 'Cycle Markers' },
  { id: 'recallCycleMarker7', label: 'Recall Cycle Marker 7', command: 'Recall Cycle Marker 7', group: 'Cycle Markers' },
  { id: 'recallCycleMarker8', label: 'Recall Cycle Marker 8', command: 'Recall Cycle Marker 8', group: 'Cycle Markers' },
  { id: 'recallCycleMarker9', label: 'Recall Cycle Marker 9', command: 'Recall Cycle Marker 9', group: 'Cycle Markers' },
  { id: 'recallCycleMarkerX', label: 'Recall Cycle Marker X', command: 'Recall Cycle Marker X', group: 'Cycle Markers' },
  { id: 'inputPunchInPosition', label: 'Input Punch In Position', command: 'Input Punch In Position', group: 'Punch (Extra)' },
  { id: 'inputPunchOutPosition', label: 'Input Punch Out Position', command: 'Input Punch Out Position', group: 'Punch (Extra)' },
  { id: 'setPunchPointsToSelection', label: 'Set Punch Points To Selection', command: 'Set Punch Points To Selection', group: 'Punch (Extra)' },
  { id: 'syncPunchToCycle', label: 'Sync Punch To Cycle', command: 'Sync Punch To Cycle', group: 'Punch (Extra)' },
  { id: 'toPunchInPosition', label: 'To Punch In Position', command: 'To Punch In Position', group: 'Punch (Extra)' },
  { id: 'toPunchOutPosition', label: 'To Punch Out Position', command: 'To Punch Out Position', group: 'Punch (Extra)' },
  { id: 'playUntilNextMarker', label: 'Play until Next Marker', command: 'Play until Next Marker', group: 'Marker Misc' },
  { id: 'toMarkerX', label: 'To Marker X', command: 'To Marker X', group: 'Marker Misc' },
  { id: 'toggleCycleFollowsMarkers', label: 'Toggle Cycle Follows Markers', command: 'Toggle: Cycle follows when locating to Markers', group: 'Marker Misc' },
  { id: 'playSelectionRange', label: 'Play Selection Range', command: 'Play Selection Range', group: 'Selection Playback' },
  { id: 'playSelectionSolo', label: 'Play Selection Solo', command: 'Play Selection Solo', group: 'Selection Playback' },
  { id: 'playFromSelectionEnd', label: 'Play from Selection End', command: 'Play from Selection End', group: 'Selection Playback' },
  { id: 'playFromSelectionStart', label: 'Play from Selection Start', command: 'Play from Selection Start', group: 'Selection Playback' },
  { id: 'playUntilSelectionEnd', label: 'Play until Selection End', command: 'Play until Selection End', group: 'Selection Playback' },
  { id: 'playUntilSelectionStart', label: 'Play until Selection Start', command: 'Play until Selection Start', group: 'Selection Playback' },
  { id: 'postRollFromSelectionEnd', label: 'Post-roll from Selection End', command: 'Post-roll from Selection End', group: 'Selection Playback' },
  { id: 'postRollFromSelectionStart', label: 'Post-roll from Selection Start', command: 'Post-roll from Selection Start', group: 'Selection Playback' },
  { id: 'preRollToSelectionEnd', label: 'Pre-roll to Selection End', command: 'Pre-roll to Selection End', group: 'Selection Playback' },
  { id: 'preRollToSelectionStart', label: 'Pre-roll to Selection Start', command: 'Pre-roll to Selection Start', group: 'Selection Playback' },
  { id: 'locateSelection', label: 'Locate Selection', command: 'Locate Selection', group: 'Loop/Locate Selection' },
  { id: 'locateSelectionEnd', label: 'Locate Selection End', command: 'Locate Selection End', group: 'Loop/Locate Selection' },
  { id: 'loopSelection', label: 'Loop Selection', command: 'Loop Selection', group: 'Loop/Locate Selection' },
  { id: 'loopSelectionSolo', label: 'Loop Selection Solo', command: 'Loop Selection Solo', group: 'Loop/Locate Selection' },
  { id: 'locateNextEvent', label: 'Locate Next Event', command: 'Locate Next Event', group: 'Event/Hitpoint Nav' },
  { id: 'locatePreviousEvent', label: 'Locate Previous Event', command: 'Locate Previous Event', group: 'Event/Hitpoint Nav' },
  { id: 'locateNextHitpoint', label: 'Locate Next Hitpoint', command: 'Locate Next Hitpoint', group: 'Event/Hitpoint Nav' },
  { id: 'locatePreviousHitpoint', label: 'Locate Previous Hitpoint', command: 'Locate Previous Hitpoint', group: 'Event/Hitpoint Nav' },
  { id: 'fastRewind', label: 'Fast Rewind', command: 'Fast Rewind', group: 'Transport Extras' },
  { id: 'fastForward', label: 'Fast Forward', command: 'Fast Forward', group: 'Transport Extras' },
  { id: 'gotoEnd', label: 'Goto End', command: 'Goto End', group: 'Transport Extras' },
  { id: 'startStop', label: 'Start/Stop', command: 'StartStop', group: 'Transport Extras' },
  { id: 'startStopPreview', label: 'Start/Stop Preview', command: 'StartStop Preview', group: 'Transport Extras' },
  { id: 'restart', label: 'Restart', command: 'Restart', group: 'Restart/Start Position' },
  { id: 'returnToStartPosition', label: 'Return to Start Position', command: 'Return to Start Position', group: 'Restart/Start Position' },
  { id: 'activateReturnToStartPosition', label: 'Activate Return to Start Position', command: 'Activate Return to Start Position', group: 'Restart/Start Position' },
  { id: 'nudgeCursorRight', label: 'Nudge Cursor Right', command: 'Nudge Cursor Right', group: 'Nudge Cursor' },
  { id: 'nudgeCursorLeft', label: 'Nudge Cursor Left', command: 'Nudge Cursor Left', group: 'Nudge Cursor' },
  { id: 'nudgeCursorMinus5Seconds', label: 'Nudge Cursor -5s', command: 'Nudge Cursor -5 Seconds', group: 'Nudge Cursor' },
  { id: 'nudgeCursorPlus5Seconds', label: 'Nudge Cursor +5s', command: 'Nudge Cursor +5 Seconds', group: 'Nudge Cursor' },
  { id: 'nudgeCursorMinus10Seconds', label: 'Nudge Cursor -10s', command: 'Nudge Cursor -10 Seconds', group: 'Nudge Cursor' },
  { id: 'nudgeCursorPlus10Seconds', label: 'Nudge Cursor +10s', command: 'Nudge Cursor +10 Seconds', group: 'Nudge Cursor' },
  { id: 'nudgeCursorMinus20Seconds', label: 'Nudge Cursor -20s', command: 'Nudge Cursor -20 Seconds', group: 'Nudge Cursor' },
  { id: 'nudgeCursorPlus20Seconds', label: 'Nudge Cursor +20s', command: 'Nudge Cursor +20 Seconds', group: 'Nudge Cursor' },
  { id: 'nudgePlus1Frame', label: 'Nudge +1 Frame', command: 'Nudge +1 Frame', group: 'Nudge Frame/Step' },
  { id: 'nudgeMinus1Frame', label: 'Nudge -1 Frame', command: 'Nudge -1 Frame', group: 'Nudge Frame/Step' },
  { id: 'stepBar', label: 'Step Bar', command: 'Step Bar', group: 'Nudge Frame/Step' },
  { id: 'stepBackBar', label: 'Step Back Bar', command: 'Step Back Bar', group: 'Nudge Frame/Step' },
  { id: 'jogLeft', label: 'Jog Left', command: 'Jog Left', group: 'Jog' },
  { id: 'jogRight', label: 'Jog Right', command: 'Jog Right', group: 'Jog' },
  { id: 'shuttlePlay1x', label: 'Shuttle Play 1x', command: 'Shuttle Play 1x', group: 'Shuttle' },
  { id: 'shuttlePlay2x', label: 'Shuttle Play 2x', command: 'Shuttle Play 2x', group: 'Shuttle' },
  { id: 'shuttlePlay4x', label: 'Shuttle Play 4x', command: 'Shuttle Play 4x', group: 'Shuttle' },
  { id: 'shuttlePlay8x', label: 'Shuttle Play 8x', command: 'Shuttle Play 8x', group: 'Shuttle' },
  { id: 'shuttlePlayHalfX', label: 'Shuttle Play 1/2x', command: 'Shuttle Play 1/2x', group: 'Shuttle' },
  { id: 'shuttlePlayQuarterX', label: 'Shuttle Play 1/4x', command: 'Shuttle Play 1/4x', group: 'Shuttle' },
  { id: 'shuttlePlayEighthX', label: 'Shuttle Play 1/8x', command: 'Shuttle Play 1/8x', group: 'Shuttle' },
  { id: 'shuttlePlayReverse1x', label: 'Shuttle Play Reverse 1x', command: 'Shuttle Play Reverse 1x', group: 'Shuttle' },
  { id: 'shuttlePlayReverse2x', label: 'Shuttle Play Reverse 2x', command: 'Shuttle Play Reverse 2x', group: 'Shuttle' },
  { id: 'shuttlePlayReverse4x', label: 'Shuttle Play Reverse 4x', command: 'Shuttle Play Reverse 4x', group: 'Shuttle' },
  { id: 'shuttlePlayReverse8x', label: 'Shuttle Play Reverse 8x', command: 'Shuttle Play Reverse 8x', group: 'Shuttle' },
  { id: 'shuttlePlayReverseHalfX', label: 'Shuttle Play Reverse 1/2x', command: 'Shuttle Play Reverse 1/2x', group: 'Shuttle' },
  { id: 'shuttlePlayReverseQuarterX', label: 'Shuttle Play Reverse 1/4x', command: 'Shuttle Play Reverse 1/4x', group: 'Shuttle' },
  { id: 'shuttlePlayReverseEighthX', label: 'Shuttle Play Reverse 1/8x', command: 'Shuttle Play Reverse 1/8x', group: 'Shuttle' },
  { id: 'audioRecordMode', label: 'Audio Record Mode', command: 'Audio Record Mode', group: 'Record Modes' },
  { id: 'globalRetrospectiveRecord', label: 'Global Retrospective Record', command: 'Global Retrospective Record', group: 'Record Modes' },
  { id: 'lockRecord', label: 'Lock Record', command: 'Lock Record', group: 'Record Modes' },
  { id: 'midiCycleRecordMode', label: 'MIDI Cycle Record Mode', command: 'MIDI Cycle Record Mode', group: 'Record Modes' },
  { id: 'midiRecordAutoQuantize', label: 'MIDI Record Auto Quantize', command: 'MIDI Record Auto Quantize', group: 'Record Modes' },
  { id: 'midiRecordMode', label: 'MIDI Record Mode', command: 'MIDI Record Mode', group: 'Record Modes' },
  { id: 'reRecordOnOff', label: 'Re-Record On/Off', command: 'Re-Record on/off', group: 'Record Modes' },
  { id: 'startMode', label: 'Start Mode', command: 'Start Mode', group: 'Record Modes' },
  { id: 'startRecordAtLeftLocator', label: 'Start Record at Left Locator', command: 'Start Record at Left Locator', group: 'Record Modes' },
  { id: 'unlockRecord', label: 'Unlock Record', command: 'Unlock Record', group: 'Record Modes' },
  { id: 'midiRetrospectiveRecordEmptyAllBuffers', label: 'MIDI Retro Record: Empty Buffers', command: 'MIDI Retrospective Record: Empty All Buffers', group: 'MIDI Retrospective Record' },
  { id: 'midiRetrospectiveRecordInsertCycle', label: 'MIDI Retro Record: Insert Cycle', command: 'MIDI Retrospective Record: Insert from Track Input as Cycle Recording', group: 'MIDI Retrospective Record' },
  { id: 'midiRetrospectiveRecordInsertLinear', label: 'MIDI Retro Record: Insert Linear', command: 'MIDI Retrospective Record: Insert from Track Input as Linear Recording', group: 'MIDI Retrospective Record' },
  { id: 'inputTempo', label: 'Input Tempo', command: 'Input Tempo', group: 'Tempo/Time' },
  { id: 'inputTimeSignature', label: 'Input Time Signature', command: 'Input Time Signature', group: 'Tempo/Time' },
  { id: 'precountOn', label: 'Precount On', command: 'Precount On', group: 'Pre/Post-Roll & Sync' },
  { id: 'projectSynchronizationSetup', label: 'Project Sync Setup', command: 'Project Synchronization Setup', group: 'Pre/Post-Roll & Sync' },
  { id: 'useExternalSync', label: 'Use External Sync', command: 'Use External Sync', group: 'Pre/Post-Roll & Sync' },
  { id: 'usePostRoll', label: 'Use Post-roll', command: 'Use Post-roll', group: 'Pre/Post-Roll & Sync' },
  { id: 'usePrePostRoll', label: 'Use Pre-/Post-Roll', command: 'Use Pre-/Post-Roll', group: 'Pre/Post-Roll & Sync' },
  { id: 'usePreRoll', label: 'Use Pre-roll', command: 'Use Pre-roll', group: 'Pre/Post-Roll & Sync' },
  { id: 'editMode', label: 'Edit Mode', command: 'Edit Mode', group: 'Setup/Misc' },
  { id: 'exchangeTimeFormats', label: 'Exchange Time Formats', command: 'Exchange Time Formats', group: 'Setup/Misc' },
  { id: 'metronomeSetup', label: 'Metronome Setup', command: 'Metronome Setup', group: 'Setup/Misc' },
  { id: 'panel', label: 'Panel', command: 'Panel', group: 'Setup/Misc' },
  { id: 'tempoTrackRehearsalModeOnOff', label: 'Tempo Track Rehearsal Mode', command: 'Tempo Track Rehearsal Mode On/Off', group: 'Setup/Misc' },
]
